'use client'

import TaxAdvantagedWithdrawalCalculator from '@/components/TaxAdvantagedWithdrawalCalculator'

export default function TaxAdvantagedWithdrawalCalculatorPage() {
  const faqs = [
    { question: 'What is tax-advantaged withdrawal sequencing?', answer: 'Tax-advantaged withdrawal order: 1) RMDs (mandatory), 2) Traditional to fill low brackets, 3) Taxable (0% LTCG in low brackets), 4) Roth last. Goal: minimize total tax over retirement. Traditional first reduces RMDs later. Taxable account: LTCG at 0% if income under $47K single, $94K married. Roth: tax-free, no RMDs, save for high-income years, emergencies, legacy. Order varies by individual situation.' },
    { question: 'Should I withdraw from Traditional or Roth first?', answer: 'Generally: Traditional first (to fill low brackets, reduce RMDs). Roth last (tax-free growth, flexibility). Exceptions: high current bracket, low expected future bracket - use Roth. Roth conversion years: use Traditional to fill brackets after conversion. Medicare IRMAA years: use Roth (not counted). SS 85% taxable threshold: use Roth to stay below. Plan multi-year strategy, not year-by-year. Consider: bracket management, SS taxation, IRMAA, RMDs, legacy goals.' },
    { question: 'How does withdrawal order affect Social Security taxation?', answer: 'SS taxation based on combined income: AGI + tax-exempt interest + 50% SS. Traditional withdrawals increase AGI, potentially making SS 50% or 85% taxable. Roth withdrawals do NOT count toward combined income. Strategy: use Roth in years where Traditional withdrawal would push SS to 85%. Example: combined income $43K married, need $5K. Traditional: $48K combined, SS 85% taxable. Roth: stays $43K, SS 50% taxable. Roth ideal for SS threshold management.' },
    { question: 'What is the 0% long-term capital gains bracket?', answer: 'LTCG 0% bracket: income under $47,025 single, $94,050 married (2024). Taxable account withdrawals can be tax-free if stay in this bracket. Strategy: in low-income years (early retirement before SS/RMD), withdraw from taxable account. Use Traditional to fill ordinary income brackets, then taxable for LTCG at 0%. Example: need $60K, withdraw $47K Traditional (12% bracket), $13K taxable (0% LTCG). Effective rate: much lower than all Traditional.' },
    { question: 'How to optimize withdrawals to avoid Medicare IRMAA?', answer: 'IRMAA based on MAGI from 2 years prior. Traditional withdrawals count toward MAGI, Roth does not. Strategy: use Roth in years affecting IRMAA (age 63-65 for Medicare at 65). Manage Traditional withdrawals to stay below IRMAA thresholds. Thresholds 2024: under $103K single, under $206K married = standard premium. Above: surcharge up to $479/mo extra. Plan 2 years ahead. QCD from IRA reduces MAGI. Roth conversions before Medicare age reduce future RMDs.' },
  ]
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity: faqs.map(faq => ({'@type':'Question',name: faq.question,acceptedAnswer:{'@type':'Answer',text: faq.answer}}))})}}/><TaxAdvantagedWithdrawalCalculator /></>)
}
