'use client'

import CharitableDonationTaxCalculator from '@/components/CharitableDonationTaxCalculator'

export default function CharitableDonationTaxCalculatorPage() {
  const faqs = [
    { question: 'How much charitable donation can I deduct?', answer: 'Deduction limits: cash donations up to 60% of AGI. Appreciated assets (stocks) up to 30% of AGI. Excess carries forward 5 years. Must itemize to deduct. Standard deduction $14,600 single/$29,200 married. If donations + other deductions less than standard: no tax benefit. Bunch donations: donate 2-3 years worth in one year to exceed standard. Donor-advised fund: bunch donations, distribute over years. Qualified Charitable Distribution (QCD): age 70.5+, direct from IRA, excluded from income (better than deduction).' },
    { question: 'What is the best way to donate appreciated assets?', answer: 'Donate appreciated stock directly to charity: avoid capital gains tax, deduct fair market value (up to 30% AGI). Never donate depreciated stock: sell first, deduct loss, then donate cash. Best stocks to donate: long-held, highly appreciated. Example: bought $5K, now $20K. Donate: $20K deduction, $0 capital gains. Sell then donate: $15K capital gains tax, $20K deduction. Save significant tax by donating directly. Get appraisal for non-public assets. Use donor-advised fund for batching donations.' },
    { question: 'What is a donor-advised fund (DAF)?', answer: 'DAF: irrevocable donation to fund, immediate tax deduction, distribute to charities over time. Benefits: bunch donations in high-income year, distribute later. Donate appreciated assets: avoid capital gains, full deduction. Low minimum: $5K to open many DAFs. Fees: administrative fee ~0.6%. Cannot: receive benefit from donation, recommend specific grant to self. Strategy: donate in high-income year (higher deduction value), grant in lower-income years. Good for: irregular income, bunching strategy, appreciated assets.' },
    { question: 'What donations are not tax deductible?', answer: 'Not deductible: donations to individuals, political campaigns/parties, foreign charities (most), private non-operating foundations, donations where you receive benefit (concert tickets, auction items above fair value), donations of time/services (mileage deductible), donations to for-profit entities. Check charity eligibility: IRS 501(c)(3) public charity. Verify on IRS Tax Exempt Organization Search. Keep records: receipt from charity, bank records, for non-cash over $500: Form 8283. Appraisal required for non-cash over $5,000.' },
    { question: 'What records do I need for charitable donations?', answer: 'Cash donations: bank record (check, credit card statement) OR written receipt from charity. Must show: charity name, date, amount. Donations $250+: written acknowledgment from charity stating no goods/services received (or value of goods). Non-cash under $500: receipt from charity, description of items. Non-cash $500-$5,000: receipt + Form 8283. Non-cash over $5,000: appraisal + Form 8283 Section B. Stocks: brokerage statement showing transfer. Keep records 3-7 years. File Form 8283 for non-cash over $500. Charities must provide acknowledgment by filing deadline or extended deadline.' },
  ]
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity: faqs.map(faq => ({'@type':'Question',name: faq.question,acceptedAnswer:{'@type':'Answer',text: faq.answer}}))})}}/><CharitableDonationTaxCalculator /></>)
}
