'use client'

import EstateTaxPlanningCalculator from '@/components/EstateTaxPlanningCalculator'

export default function EstateTaxPlanningCalculatorPage() {
  const faqs = [
    { question: 'What is the federal estate tax exemption?', answer: '2024 exemption: $13.61 million per person, $27.22 million married (portable). TCJA sunsets end of 2025: projected exemption drops to ~$7M per person in 2026. Estate over exemption: taxed at 18-40% (max 40%). Example: $15M estate, exemption $7M, taxable $8M, tax ~$3.2M (40%). Married: double exemption if portability elected. File estate tax return Form 706 within 9 months of death to claim portability even if no tax due.' },
    { question: 'What is estate tax portability?', answer: 'Portability: deceased spouse unused exemption transfers to surviving spouse. Married couples can shield up to double exemption ($27M+ in 2024). Requirement: file Form 706 within 9 months of first spouse death (can extend 6 months). Elect portability even if no estate tax due. Example: first spouse dies with $5M estate, exemption $13.6M, unused $8.6M transfers to survivor. Survivor now has $13.6M + $8.6M = $22.2M exemption.' },
    { question: 'How to reduce estate tax?', answer: 'Strategies: 1) Annual gift exclusion: $18K per person per year, unlimited recipients. 2) Lifetime gifts: use exemption during life. 3) Irrevocable trusts: remove assets from estate. 4) Life insurance trust (ILIT): proceeds excluded. 5) Charitable remainder trust: income + deduction. 6) Family limited partnership: valuation discounts. 7) Spousal transfer: unlimited marital deduction. 8) QPRT: remove home at reduced value. Plan before TCJA sunset 2025 if estate over projected $7M exemption.' },
    { question: 'Which states have estate or inheritance tax?', answer: 'Estate tax states: NY, MA, CT, OR, IL, MN, MD, HI, VT, WA, DC. Tax on estate before distribution. Lower exemptions than federal (MA $2M). Inheritance tax states: NJ, PA, IA, KY, NE. Tax on heir based on relationship. Spouse usually exempt, children lower rate, others higher. No state estate tax: CA, TX, FL, AZ, NV, CO, most others. State tax adds to federal. Plan for both if applicable.' },
    { question: 'Does life insurance count toward estate?', answer: 'Life insurance proceeds INCLUDED if: policy owned by insured, proceeds payable to estate, beneficiary is estate. Life insurance EXCLUDED if: policy owned by ILIT (irrevocable life insurance trust), beneficiary is individual (not estate). ILIT: transfer policy to trust 3+ years before death (3-year rule). Pay premiums via annual gift exclusion. Trust owns policy, pays premiums, distributes proceeds to heirs tax-free. Large policy: use ILIT to keep proceeds out of estate.' },
  ]
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity: faqs.map(faq => ({'@type':'Question',name: faq.question,acceptedAnswer:{'@type':'Answer',text: faq.answer}}))})}}/><EstateTaxPlanningCalculator /></>)
}
