'use client'

import DividendTaxCalculator from '@/components/DividendTaxCalculator'

export default function DividendTaxCalculatorPage() {
  const faqs = [
    { question: 'What is the difference between qualified and ordinary dividends?', answer: 'Qualified dividends: meet holding period (60+ days in 121-day period), from US or qualified foreign corporation. Taxed at LTCG rates: 0%, 15%, or 20%. Ordinary (non-qualified) dividends: REITs, MLPs, money market, short holding period. Taxed at ordinary income rates (10-37%). Qualified dividends save significant tax. Example: $10K qualified at 15% = $1,500 tax. Same $10K ordinary at 24% = $2,400 tax. Save $900.' },
    { question: 'What dividend tax rate do I pay?', answer: 'Qualified dividends: 0% if income under $47K single/$94K married, 15% for most taxpayers, 20% if income over $519K single/$584K married. Ordinary dividends: taxed at your marginal income rate (10-37%). Most taxpayers pay 15% on qualified. State tax: most states tax all dividends as ordinary income. NIIT: 3.8% additional for high earners (over $200K single, $250K married). Effective rate: 15% qualified + state rate + NIIT if applicable.' },
    { question: 'How long must I hold stock for qualified dividends?', answer: 'Common stock: hold 60+ days during 121-day period starting 60 days before ex-dividend date. Preferred stock: 90+ days during 181-day period. Must hold around ex-dividend date. Buy before ex-dividend, hold through required period. Days count from purchase date. If held less: dividend taxed as ordinary income. ETF/mutual fund: fund reports qualified percentage on 1099-DIV. Check form for qualified amount.' },
    { question: 'Are REIT dividends qualified?', answer: 'REIT dividends generally NOT qualified. Taxed as ordinary income at marginal rate. However: portion may be return of capital (reduces basis, taxed later as gain), capital gains portion (qualified), qualified dividend portion (small). Most REIT dividends: ordinary income. MLP dividends: also non-qualified, may have deductions. Money market dividends: always ordinary. Strategy: REITs in tax-advantaged accounts (IRA, 401k) avoid immediate tax on distributions.' },
    { question: 'How does dividend tax work with state tax?', answer: 'Most states tax dividends as ordinary income at state rate. No preferential treatment for qualified dividends. Example: California 13.3% on all dividends. Texas/Florida/Washington: 0% state tax. Total tax: federal qualified rate + state rate + NIIT if applicable. Example: 15% federal + 5% state = 20% effective rate. Strategy: consider state when choosing dividend investments. Tax-advantaged accounts avoid state tax on dividends in most states.' },
  ]
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity: faqs.map(faq => ({'@type':'Question',name: faq.question,acceptedAnswer:{'@type':'Answer',text: faq.answer}}))})}}/><DividendTaxCalculator /></>)
}
