'use client'

import AssetLocationCalculator from '@/components/AssetLocationCalculator'

export default function AssetLocationCalculatorPage() {
  const faqs = [
    { question: 'What is asset location in investing?', answer: 'Asset location: placing investments in optimal account type for tax efficiency. Taxable account: stocks for LTCG (0-20%), tax-efficient ETFs, municipal bonds. Traditional IRA/401k: bonds, REITs, high-yield assets (deferred tax). Roth IRA: highest growth potential assets (tax-free forever). Goal: minimize total tax over lifetime. Different from asset allocation (portfolio mix). Asset location optimizes WHERE to hold each asset class.' },
    { question: 'What assets should go in taxable accounts?', answer: 'Taxable account best for: stocks (LTCG rates 0-20%), tax-efficient index ETFs, municipal bonds (tax-exempt), long-term holdings, international stocks (foreign tax credit available). Avoid in taxable: bonds (interest taxed as ordinary income), REITs (dividends taxed as ordinary), high-turnover funds (short-term gains), actively traded stocks. Tax-loss harvesting works in taxable only. Consider: holding period for LTCG, state tax on dividends, foreign tax credit.' },
    { question: 'What assets should go in Traditional IRA/401k?', answer: 'Traditional IRA/401k best for: bonds (interest taxed as ordinary anyway), bond funds, REITs (dividends taxed as ordinary), high-yield assets, actively traded funds, assets with high turnover. Tax deferred: all earnings taxed as ordinary at withdrawal. Since bonds/REITs taxed at ordinary rates anyway, deferral makes sense. RMDs at 73: plan drawdown. Convert to Roth before RMDs for tax-free growth. Employer match: free money, always contribute first.' },
    { question: 'What assets should go in Roth IRA?', answer: 'Roth IRA best for: highest growth potential (tax-free forever), small-cap stocks, growth stocks, emerging markets, sector ETFs, assets expected to multiply. Roth: contributions taxed now, growth tax-free forever. Advantage: 40+ years of tax-free growth. Best for young investors, high growth assets. Roth conversion: convert Traditional holdings expected to grow significantly. No RMDs: hold forever, pass to heirs tax-free. Use Roth for assets with highest expected return.' },
    { question: 'How to optimize asset location?', answer: 'Steps: 1) Determine asset allocation (stocks/bonds mix). 2) Fill tax-advantaged accounts with tax-inefficient assets (bonds, REITs). 3) Put tax-efficient assets in taxable (stocks, ETFs). 4) Roth for highest growth potential. 5) Consider account sizes: may need to hold some stocks in Traditional if Roth small. 6) Rebalance across accounts: adjust location as accounts grow. 7) Factor in withdrawal timing: taxable for flexibility, Traditional for RMDs, Roth for late retirement. Example: 60/40 portfolio. Bonds in Traditional, stocks in taxable, growth stocks in Roth.' },
  ]
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity: faqs.map(faq => ({'@type':'Question',name: faq.question,acceptedAnswer:{'@type':'Answer',text: faq.answer}}))})}}/><AssetLocationCalculator /></>)
}
