'use client'

import TaxBracketThresholdCalculator from '@/components/TaxBracketThresholdCalculator'

export default function TaxBracketThresholdCalculatorPage() {
  const faqs = [
    { question: 'What are the 2024 federal tax brackets?', answer: 'Single: 10% ($0-$11,600), 12% ($11,600-$47,150), 22% ($47,150-$100,525), 24% ($100,525-$191,950), 32% ($191,950-$243,725), 35% ($243,725-$609,350), 37% (over $609,350). Married: 10% ($0-$23,200), 12% ($23,200-$94,300), 22% ($94,300-$201,050), 24% ($201,050-$383,900), 32% ($383,900-$487,450), 35% ($487,450-$731,200), 37% (over $731,200). Standard deduction: $14,600 single/$29,200 married. Marginal rate: rate on last dollar earned. Effective rate: total tax / total income. Brackets indexed for inflation annually.' },
    { question: 'How do tax brackets work?', answer: 'Progressive tax: each bracket taxed at its rate. Not: all income taxed at highest bracket rate. Example: $50K single. First $11,600 at 10% = $1,160. Next $35,550 at 12% = $4,266. Total tax $5,426. Effective rate 10.9%. Marginal rate 12%. Benefit: fill lower brackets first. Strategy: manage income to stay in lower bracket. Use pre-tax contributions to reduce taxable income. Plan income timing: defer income to lower bracket year. Roth conversion: fill bracket without exceeding next bracket threshold.' },
    { question: 'How can I stay in a lower tax bracket?', answer: 'Strategies: 1) Pre-tax 401k/IRA contributions (reduces taxable income). 2) HSA contributions (triple tax-free). 3) Defer income to next year (if close to threshold). 4) Tax-loss harvesting (offset gains). 5) Business expense deductions (self-employed). 6) Charitable donations (if itemizing). 7) Education credits (reduce tax, not income). 8) Roth conversion: careful timing to fill bracket. Example: $95K income, bracket ends $100,525. Contribute $6K to 401k, stay in 22% bracket. Each bracket jump saves significant tax.' },
    { question: 'What is the difference between marginal and effective tax rate?', answer: 'Marginal rate: rate on your last dollar of income (highest bracket you reach). Used for: evaluating deductions, conversions, additional income. Effective rate: total tax divided by total income. Lower than marginal due to progressive brackets. Example: $50K single, tax $5,426. Marginal 12%, effective 10.9%. Use marginal rate for decisions: contribute $1K to 401k = save $1K x marginal rate. Use effective rate for overall tax burden comparison. Strategy: minimize effective rate by filling lower brackets, using deductions.' },
    { question: 'How does the standard deduction affect my bracket?', answer: 'Standard deduction reduces taxable income before brackets apply. 2024: $14,600 single/$29,200 married. Taxable income = gross income - standard deduction - pre-tax contributions. Example: $60K gross, $6K 401k, standard $14,600 single. Taxable = $39,400. Brackets: first $11,600 at 10%, remaining $27,800 at 12%. Marginal 12%. Without standard deduction: taxable would be higher, higher bracket. Itemize if: deductions exceed standard. Standard deduction essentially shifts brackets: $0-$14,600 taxed at 0%.' },
  ]
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity: faqs.map(faq => ({'@type':'Question',name: faq.question,acceptedAnswer:{'@type':'Answer',text: faq.answer}}))})}}/><TaxBracketThresholdCalculator /></>)
}
