'use client'

import { useState } from 'react';

interface ReportData {
  calculatorName: string;
  calculatorUrl: string;
  inputs: { label: string; value: string }[];
  outputs: { label: string; value: string; description?: string }[];
  comparisonData?: { label: string; values: string[] }[];
  generatedAt: string;
}

export default function PremiumReportExport({ data }: { data: ReportData }) {
  const [isExporting, setIsExporting] = useState(false);
  const [showUpgradePrompt, setShowUpgradePrompt] = useState(false);

  const generateReportText = () => {
    const lines: string[] = [];
    
    lines.push(`=== ${data.calculatorName} Report ===`);
    lines.push(`Generated: ${data.generatedAt}`);
    lines.push(`Source: ${data.calculatorUrl}`);
    lines.push('');
    
    lines.push('INPUT PARAMETERS:');
    data.inputs.forEach((input) => {
      lines.push(`  ${input.label}: ${input.value}`);
    });
    lines.push('');
    
    lines.push('CALCULATION RESULTS:');
    data.outputs.forEach((output) => {
      lines.push(`  ${output.label}: ${output.value}`);
      if (output.description) {
        lines.push(`    (${output.description})`);
      }
    });
    lines.push('');
    
    if (data.comparisonData) {
      lines.push('COMPARISON TABLE:');
      data.comparisonData.forEach((row) => {
        lines.push(`  ${row.label}: ${row.values.join(' | ')}`);
      });
      lines.push('');
    }
    
    lines.push('DISCLAIMER:');
    lines.push('This report provides estimates only and should not be considered');
    lines.push('professional financial advice. Consult licensed professionals');
    lines.push('for personalized recommendations.');
    lines.push('');
    lines.push('Generated by Finance Tools (finance.128345827.xyz)');
    
    return lines.join('\n');
  };

  const handleExport = async () => {
    setShowUpgradePrompt(true);
  };

  const handleBasicExport = () => {
    setIsExporting(true);
    const reportText = generateReportText();
    
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.calculatorName.replace(/\s+/g, '-').toLowerCase()}-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    setIsExporting(false);
    setShowUpgradePrompt(false);
  };

  return (
    <div className="inline-block">
      <button
        onClick={handleExport}
        disabled={isExporting}
        className="btn-secondary text-sm flex items-center gap-2"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        Export Report
      </button>

      {showUpgradePrompt && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl p-6 max-w-md mx-4 shadow-xl">
            <h3 className="text-lg font-bold mb-4">Export Your Calculation Report</h3>
            
            <div className="space-y-3 mb-4">
              <div className="flex items-center gap-2 text-green-600">
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                <span>Basic Text Export (Free)</span>
              </div>
              <p className="text-sm text-gray-600">Download results as plain text file.</p>
              
              <div className="border-t pt-3 mt-3">
                <div className="flex items-center gap-2 text-primary-600">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.506a3.42 3.42 0 014.438 0a3.42 3.42 0 001.946.506a3.42 3.42 0 013.138 3.138a3.42 3.42 0 00.506 1.946a3.42 3.42 0 010 4.438a3.42 3.42 0 00-.506 1.946a3.42 3.42 0 01-3.138 3.138a3.42 3.42 0 00-1.946.506a3.42 3.42 0 01-4.438 0a3.42 3.42 0 00-1.946-.506a3.42 3.42 0 01-3.138-3.138a3.42 3.42 0 00-.506-1.946a3.42 3.42 0 010-4.438a3.42 3.42 0 00.506-1.946a3.42 3.42 0 013.138-3.138z" />
                  </svg>
                  <span className="font-medium">Premium PDF Report</span>
                </div>
                <ul className="text-sm text-gray-600 mt-2 space-y-1">
                  <li>• Professional formatted PDF document</li>
                  <li>• Visual charts and comparison tables</li>
                  <li>• Email delivery to your inbox</li>
                  <li>• No ads on report pages</li>
                </ul>
                <p className="text-sm text-primary-600 mt-2 font-medium">$4.99/month or free with annual plan</p>
              </div>
            </div>

            <div className="flex gap-3">
              <button
                onClick={handleBasicExport}
                className="flex-1 px-4 py-2 bg-gray-100 hover:bg-gray-200 rounded-lg text-sm font-medium"
              >
                Download Text (Free)
              </button>
              <button
                onClick={() => setShowUpgradePrompt(false)}
                className="flex-1 px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg text-sm font-medium"
              >
                Close
              </button>
            </div>
            
            <p className="text-xs text-gray-500 mt-3 text-center">
              Premium feature coming soon. Subscribe for updates.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}