'use client'

import QCDTaxBenefitCalculator from '@/components/QCDTaxBenefitCalculator'

export default function QCDTaxBenefitCalculatorPage() {
  const faqs = [
    { question: 'What is a Qualified Charitable Distribution (QCD)?', answer: 'QCD: direct transfer from IRA to qualified charity (age 70.5+). Max $105,000 per year (2024). Benefits: satisfies RMD, excluded from taxable income, reduces MAGI for SS taxation and IRMAA. Cannot deduct QCD (already excluded). Must go directly from IRA to charity (no intermediate steps). Works with Traditional IRA (401k must roll to IRA first). QCD better than cash donation for most retirees: avoids AGI increase, reduces SS/IRMAA impact.' },
    { question: 'How does QCD affect RMD?', answer: 'QCD counts toward RMD. Example: RMD $8K, QCD $5K: remaining RMD $3K. QCD can fully satisfy RMD: no additional withdrawal needed. RMD age: 73 (2024). QCD age: 70.5 (can do QCD before RMD begins). Strategy: do QCD in RMD year to reduce taxable income. QCD reduces AGI, which reduces SS taxation threshold, IRMAA MAGI. Perfect for retirees with charitable intent and RMD requirements.' },
    { question: 'Who can do a QCD?', answer: 'Age 70.5 or older. Must have Traditional IRA (401k requires rollover first). Charity: 501(c)(3) public charity (not private foundation, donor-advised fund). Transfer: direct from IRA custodian to charity (check written by custodian, not you). Cannot be to: private foundation, donor-advised fund, supporting organization, charity with conflicts. Verify charity eligibility on IRS database. Keep documentation: receipt from charity, proof of direct transfer.' },
    { question: 'How does QCD reduce Social Security taxation?', answer: 'QCD excluded from AGI, reduces combined income for SS taxation. Combined income = AGI + tax-exempt interest + 50% SS. Thresholds: $25K/$34K single, $32K/$44K married. Below: SS 0% taxable. Between: 50% taxable. Above: 85% taxable. QCD reduces AGI, potentially lowering SS taxable portion. Example: QCD $5K reduces combined income $5K, may drop from 85% to 50% taxable. Save significant tax. Roth withdrawals also excluded (same benefit). QCD + Roth for SS management.' },
    { question: 'How does QCD help avoid Medicare IRMAA?', answer: 'IRMAA based on MAGI from 2 years prior. QCD reduces MAGI, potentially avoiding IRMAA surcharge. Thresholds: $103K single, $206K married. Above: Part B surcharge up to $479/month. QCD reduces MAGI by QCD amount. Example: income $110K, QCD $10K, MAGI drops to $100K, avoids IRMAA. Plan 2 years ahead: 2024 QCD affects 2026 IRMAA. QCD better than cash donation for IRMAA management: direct MAGI reduction. Roth withdrawals also excluded (same benefit).' },
  ]
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity: faqs.map(faq => ({'@type':'Question',name: faq.question,acceptedAnswer:{'@type':'Answer',text: faq.answer}}))})}}/><QCDTaxBenefitCalculator /></>)
}
