'use client'

import SocialSecurityBenefitsCalculator from '@/components/SocialSecurityBenefitsCalculator'

export default function SocialSecurityBenefitsCalculatorPage() {
  const faqs = [
    { question: 'How is Social Security benefit calculated?', answer: 'SS benefit based on AIME (Average Indexed Monthly Earnings) from top 35 earning years. PIA formula: 90% of first $1174 + 32% of $1174-$7059 + 15% above $7059 (2024). AIME calculated by indexing earnings to inflation, selecting highest 35 years, averaging. Minimum 40 credits (10 years) required. Benefits reduced for early retirement (age 62-67), increased for delayed retirement (up to age 70, 8%/year credit). Maximum benefit at FRA: $3827 (2024). Spousal benefit: up to 50% of worker PIA.' },
    { question: 'What is full retirement age for Social Security?', answer: 'FRA depends on birth year: born 1937 or earlier: age 65. Born 1938-1942: 65 + 2 months per year. Born 1943-1954: age 66. Born 1955-1959: 66 + 2 months per year. Born 1960 or later: age 67. Claiming before FRA: permanent reduction (6.67%/year for first 3 years, 5%/year after). Claiming after FRA: delayed retirement credits (8%/year up to age 70). FRA determines eligibility for full benefit without reduction.' },
    { question: 'Can I work while receiving Social Security?', answer: 'Yes, but earnings test applies if under FRA. 2024 limits: under FRA: $22,320/year, excess earnings reduce benefits $1 for $2. Year reaching FRA: $59,520/year, $1 for $3. After FRA: no limit, full benefits regardless of earnings. Earnings test withheld benefits credited at FRA, increasing future monthly amount. Different rules for disability benefits. Self-employment income counts toward earnings test.' },
    { question: 'How does delayed retirement increase my benefit?', answer: 'Delayed retirement credits: 8% per year (for births 1943+) for each year beyond FRA up to age 70. Example: FRA 67, delay to 70: 24% increase (3 years x 8%). Benefit permanently higher. Also affects survivor benefits. Delay strategy: higher lifetime benefit if live past break-even age (~78-80). Consider health, life expectancy, other income. Maximum increase: 24% (delay 67 to 70) or 32% (delay 66 to 70 depending on FRA). COLA applies to higher benefit.' },
    { question: 'What is the maximum Social Security benefit?', answer: 'Maximum benefit at FRA (2024): $3,827/month. Maximum at age 70: ~$4,873/month (with delayed credits). Requirements for maximum: 35 years of maximum taxable earnings ($168,600 in 2024), delay claiming to age 70. Average benefit: ~$1,900/month. Benefit depends on earnings history, not a fixed maximum. High earners early in career indexed to inflation. Only earnings up to wage base cap counted ($168,600 in 2024). Spousal benefit capped at 50% of worker PIA.' },
  ]
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity: faqs.map(faq => ({'@type':'Question',name: faq.question,acceptedAnswer:{'@type':'Answer',text: faq.answer}}))})}}/><SocialSecurityBenefitsCalculator /></>)
}
