'use client'

import CapitalGainsTaxCalculator from '@/components/CapitalGainsTaxCalculator'

export default function CapitalGainsTaxCalculatorPage() {
  const faqs = [
    { question: 'What is the capital gains tax rate?', answer: 'Short-term (held under 1 year): taxed at ordinary income rates (10-37%). Long-term (held over 1 year): 0%, 15%, or 20% based on taxable income. 2024 LTCG brackets (single): 0% under $47,025, 15% under $518,900, 20% above. Married brackets: 0% under $94,050, 15% under $583,750, 20% above. NIIT adds 3.8% for high income (over $200K single, $250K married). State tax: most states tax gains as ordinary income.' },
    { question: 'How to minimize capital gains tax?', answer: 'Strategies: hold investments over 1 year for lower LTCG rates. Tax-loss harvesting: offset gains with losses, deduct up to $3,000 against ordinary income. Time gains: realize in years with low ordinary income to stay in 0% LTCG bracket. Use tax-advantaged accounts (401k, IRA) for active trading. Donate appreciated assets to charity (avoid gain, get deduction). Avoid wash sale rule: 30-day waiting period after selling for loss. Consider opportunity zones for deferred gains.' },
    { question: 'What is tax-loss harvesting?', answer: 'Sell losing investments to offset realized gains. Offset short-term gains first (higher tax rate). Up to $3,000 excess loss deductible against ordinary income per year. Remaining losses carry forward indefinitely. Wash sale rule: cannot repurchase same/similar security within 30 days before or after sale. Harvest at year-end or throughout year. Consider: transaction costs, future recovery, wash sale rule, portfolio allocation. Works best with volatile investments.' },
    { question: 'Does capital gains count toward Social Security taxation?', answer: 'Yes, capital gains count toward combined income for Social Security taxation. Combined income = AGI + tax-exempt interest + 50% of SS benefits. Capital gains increase combined income, potentially making more SS taxable (50% or 85% threshold). LTCG taxed separately at capital gains rates but affects SS taxation threshold. Strategy: use Roth withdrawals (not counted), time gains carefully, harvest losses to reduce AGI.' },
    { question: 'What is the wash sale rule?', answer: 'Wash sale rule: cannot claim loss if repurchase same or substantially identical security within 30 days before or after sale. Applies to: same stock/ETF, similar ETFs tracking same index, options on same stock. Does NOT apply to: different stocks in same sector, bonds, different ETFs tracking different indices. Loss disallowed: added to basis of repurchased shares, defers deduction until later sale. Applies across all accounts (IRA, 401k, taxable). Wait 31+ days to repurchase.' },
  ]
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity: faqs.map(faq => ({'@type':'Question',name: faq.question,acceptedAnswer:{'@type':'Answer',text: faq.answer}}))})}}/><CapitalGainsTaxCalculator /></>)
}
