'use client'

import RothConversionLadderCalculator from '@/components/RothConversionLadderCalculator'

export default function RothConversionLadderCalculatorPage() {
  const faqs = [
    { question: 'What is a Roth conversion ladder?', answer: 'Roth conversion ladder: convert Traditional IRA to Roth during early retirement (before SS/RMD), wait 5 years, then withdraw conversion contributions tax-free. 5-year rule: each conversion accessible after 5 years (no age requirement). Benefits: tax-free income during bridge years (early retirement to SS age), avoid RMDs, reduce future tax burden. Strategy: convert during low-income years before retirement or in early retirement before SS begins.' },
    { question: 'How does the 5-year rule work for Roth conversions?', answer: 'Each Roth conversion has its own 5-year clock. After 5 years, conversion contributions can be withdrawn tax-free regardless of age. Ordering: contributions first, then conversions, then earnings. Earnings: tax-free only after 59.5 AND account open 5+ years. Early withdrawal penalty: 10% on earnings before 59.5. Conversions penalty-free after 5 years. Example: convert $20K at 55, withdraw at 60+ = tax-free. Start conversions early for 5-year clock to mature.' },
    { question: 'Can I use Roth ladder for early retirement?', answer: 'Yes. Roth ladder ideal for FIRE (early retirement). Strategy: convert during working years (age 50-55), ladder matures by retirement age (55-60). Use ladder income for bridge years (retirement to SS at 62-67). Example: retire at 55, conversions started at 50, first ladder payment at 55+5=60. Plan: convert annually for continuous ladder income. Each year provides income 5 years later. Coordinate with other income sources: taxable account, part-time work.' },
    { question: 'What is the bridge period in retirement?', answer: 'Bridge period: early retirement (55-60) to Social Security (62-67) or Medicare (65). Income needed: living expenses, healthcare (before Medicare). Roth ladder: provides tax-free income. Taxable account: LTCG at 0% in low brackets. Traditional withdrawals: fill low brackets. Strategy: Roth ladder for bridge, SS at 62 or delay to 67 for higher benefit, Medicare at 65. Healthcare before 65: ACA marketplace, COBRA, spouse coverage, HSA accumulation.' },
    { question: 'Should I convert before or after retirement?', answer: 'Convert during working years: higher marginal rate (but start 5-year clock early). Convert in early retirement: lower marginal rate (but wait 5 years). Hybrid: convert some now (for ladder income in 5 years), more in retirement (lower tax). Consider: current vs future marginal rate, RMD reduction, SS taxation, IRMAA. Best: convert in low-income years (early retirement before SS). Convert enough to fill low brackets each year. Project conversions over 10+ years for maximum benefit.' },
  ]
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity: faqs.map(faq => ({'@type':'Question',name: faq.question,acceptedAnswer:{'@type':'Answer',text: faq.answer}}))})}}/><RothConversionLadderCalculator /></>)
}
